# Generated by Django 4.1.5 on 2023-01-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="short_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
