# Generated by Django 4.1.5 on 2023-01-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.CharField(blank=True, max_length=100, null=True)),
                ("subject", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Incoterms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("incoterms", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="RequestQuote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("contact_number", models.IntegerField(blank=True, null=True)),
                (
                    "freight_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("catagories", "Catagories One"),
                            ("catagories", "Catagories Two"),
                            ("catagories", "Catagories Three"),
                            ("catagories", "Catagories Four"),
                            ("catagories", "Catagories Five"),
                        ],
                        default=None,
                        max_length=20,
                        null=True,
                    ),
                ),
                ("incoterms", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "city_of_department",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("height", models.IntegerField(blank=True, null=True)),
                ("width", models.IntegerField(blank=True, null=True)),
                ("lenght", models.IntegerField(blank=True, null=True)),
                (
                    "extra_service",
                    models.CharField(
                        choices=[
                            ("freight", "Freight"),
                            ("express Delivery", "Express Delivery"),
                            ("insurance", "Insurance"),
                            ("packaging", "Packaging"),
                        ],
                        default="freight",
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
